package executor

import (
	"bytes"
	"io"
	"os"
	"os/exec"
	"strings"
	"testing"
	"time"
)

// newTestLauncher returns a Launcher with captured stdout/stderr.
func newTestLauncher() (*Launcher, *bytes.Buffer, *bytes.Buffer) {
	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	return &Launcher{
		Stdin:  bytes.NewReader(nil),
		Stdout: stdout,
		Stderr: stderr,
	}, stdout, stderr
}

// ── Exit codes ────────────────────────────────────────────────────────────────

func TestLauncher_exitCode_zero(t *testing.T) {
	l, _, _ := newTestLauncher()
	result, err := l.Run(exec.Command("sh", "-c", "exit 0"), RunOptions{})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if result.ExitCode != 0 {
		t.Errorf("ExitCode = %d, want 0", result.ExitCode)
	}
}

func TestLauncher_exitCode_nonZero(t *testing.T) {
	l, _, _ := newTestLauncher()
	result, err := l.Run(exec.Command("sh", "-c", "exit 42"), RunOptions{})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if result.ExitCode != 42 {
		t.Errorf("ExitCode = %d, want 42", result.ExitCode)
	}
}

// ── Stdout / stderr capture ───────────────────────────────────────────────────

func TestLauncher_capturesStdout(t *testing.T) {
	l, stdout, _ := newTestLauncher()
	_, err := l.Run(exec.Command("sh", "-c", "echo hello-test"), RunOptions{})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if !strings.Contains(stdout.String(), "hello-test") {
		t.Errorf("expected stdout to contain 'hello-test', got: %q", stdout.String())
	}
}

func TestLauncher_capturesStderr(t *testing.T) {
	l, _, stderr := newTestLauncher()
	_, err := l.Run(exec.Command("sh", "-c", "echo err-msg >&2"), RunOptions{})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if !strings.Contains(stderr.String(), "err-msg") {
		t.Errorf("expected stderr to contain 'err-msg', got: %q", stderr.String())
	}
}

// ── Run ID ────────────────────────────────────────────────────────────────────

func TestLauncher_runID_autoGenerated(t *testing.T) {
	l, _, _ := newTestLauncher()
	result, err := l.Run(exec.Command("true"), RunOptions{})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if result.RunID == "" {
		t.Error("expected RunID to be auto-generated")
	}
	if !runIDPattern.MatchString(result.RunID) {
		t.Errorf("RunID %q does not match expected format", result.RunID)
	}
}

func TestLauncher_runID_explicit(t *testing.T) {
	l, _, _ := newTestLauncher()
	result, err := l.Run(exec.Command("true"), RunOptions{RunID: "my-custom-id"})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if result.RunID != "my-custom-id" {
		t.Errorf("RunID = %q, want %q", result.RunID, "my-custom-id")
	}
}

// ── Log file ──────────────────────────────────────────────────────────────────

func TestLauncher_logFile_created(t *testing.T) {
	l := &Launcher{Stdin: bytes.NewReader(nil), Stdout: io.Discard, Stderr: io.Discard}
	logDir := t.TempDir()

	result, err := l.Run(exec.Command("sh", "-c", "echo log-line"), RunOptions{
		LogDir: logDir,
		RunID:  "testrun-001",
	})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if result.LogPath == "" {
		t.Fatal("expected LogPath to be set")
	}
	data, err := os.ReadFile(result.LogPath)
	if err != nil {
		t.Fatalf("reading log: %v", err)
	}
	if !strings.Contains(string(data), "log-line") {
		t.Errorf("expected log to contain 'log-line', got: %q", string(data))
	}
}

func TestLauncher_logFile_alsoWritesToStdout(t *testing.T) {
	stdout := &bytes.Buffer{}
	l := &Launcher{Stdin: bytes.NewReader(nil), Stdout: stdout, Stderr: io.Discard}
	logDir := t.TempDir()

	_, err := l.Run(exec.Command("sh", "-c", "echo dual-output"), RunOptions{
		LogDir: logDir,
		RunID:  "testrun-002",
	})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if !strings.Contains(stdout.String(), "dual-output") {
		t.Errorf("expected stdout to still receive output when logging, got: %q", stdout.String())
	}
}

func TestLauncher_noLogDir_logPathEmpty(t *testing.T) {
	l, _, _ := newTestLauncher()
	result, err := l.Run(exec.Command("true"), RunOptions{})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if result.LogPath != "" {
		t.Errorf("expected empty LogPath when LogDir not set, got: %q", result.LogPath)
	}
}

// ── Timeout ───────────────────────────────────────────────────────────────────

func TestLauncher_timeout_killsProcess(t *testing.T) {
	l := &Launcher{Stdin: bytes.NewReader(nil), Stdout: io.Discard, Stderr: io.Discard}

	start := time.Now()
	result, err := l.Run(exec.Command("sleep", "30"), RunOptions{Timeout: 1})
	elapsed := time.Since(start)

	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if result.ExitCode == 0 {
		t.Error("expected non-zero exit code when process is killed")
	}
	if elapsed > 10*time.Second {
		t.Errorf("expected process to be killed within 10s, took %v", elapsed)
	}
}

func TestLauncher_noTimeout_processRunsToCompletion(t *testing.T) {
	l := &Launcher{Stdin: bytes.NewReader(nil), Stdout: io.Discard, Stderr: io.Discard}
	result, err := l.Run(exec.Command("sh", "-c", "sleep 0.1 && exit 0"), RunOptions{Timeout: 0})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if result.ExitCode != 0 {
		t.Errorf("ExitCode = %d, want 0", result.ExitCode)
	}
}

// ── Cleanups ──────────────────────────────────────────────────────────────────

func TestLauncher_cleanups_calledAfterRun(t *testing.T) {
	l, _, _ := newTestLauncher()
	called := false
	_, err := l.Run(exec.Command("true"), RunOptions{
		Cleanups: []func() error{
			func() error { called = true; return nil },
		},
	})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if !called {
		t.Error("expected cleanup to be called")
	}
}

func TestLauncher_cleanups_calledEvenOnNonZeroExit(t *testing.T) {
	l, _, _ := newTestLauncher()
	called := false
	result, err := l.Run(exec.Command("sh", "-c", "exit 1"), RunOptions{
		Cleanups: []func() error{
			func() error { called = true; return nil },
		},
	})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if result.ExitCode != 1 {
		t.Errorf("ExitCode = %d, want 1", result.ExitCode)
	}
	if !called {
		t.Error("expected cleanup to be called even on non-zero exit")
	}
}

func TestLauncher_cleanups_multipleCalledInOrder(t *testing.T) {
	l, _, _ := newTestLauncher()
	var order []int
	_, err := l.Run(exec.Command("true"), RunOptions{
		Cleanups: []func() error{
			func() error { order = append(order, 1); return nil },
			func() error { order = append(order, 2); return nil },
			func() error { order = append(order, 3); return nil },
		},
	})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if len(order) != 3 || order[0] != 1 || order[1] != 2 || order[2] != 3 {
		t.Errorf("cleanups called in wrong order: %v", order)
	}
}

// ── waitExitCode ──────────────────────────────────────────────────────────────

func TestWaitExitCode_zero(t *testing.T) {
	cmd := exec.Command("true")
	if err := cmd.Start(); err != nil {
		t.Fatal(err)
	}
	code, err := waitExitCode(cmd)
	if err != nil {
		t.Fatalf("waitExitCode: %v", err)
	}
	if code != 0 {
		t.Errorf("code = %d, want 0", code)
	}
}

func TestWaitExitCode_nonZero(t *testing.T) {
	cmd := exec.Command("sh", "-c", "exit 7")
	if err := cmd.Start(); err != nil {
		t.Fatal(err)
	}
	code, err := waitExitCode(cmd)
	if err != nil {
		t.Fatalf("waitExitCode: %v", err)
	}
	if code != 7 {
		t.Errorf("code = %d, want 7", code)
	}
}
