// Package containers generates the podman/OCI configuration that a sandboxed
// rootless container runtime needs to work inside an inner sandbox.
package containers

import (
	"fmt"
	"os"
	"path/filepath"
)

// CgroupManagerCgroupfs and CgroupManagerSystemd are the two values accepted
// by [sandbox] cgroup_manager (and by podman's engine.cgroup_manager).
const (
	CgroupManagerCgroupfs = "cgroupfs"
	CgroupManagerSystemd  = "systemd"
)

// OverrideEnvVar is the podman environment variable that points at a
// containers.conf fragment merged ON TOP of the regular configuration
// (/etc/containers/containers.conf, ~/.config/containers/containers.conf).
// Because it is a merge, injecting it leaves the user's own files untouched.
const OverrideEnvVar = "CONTAINERS_CONF_OVERRIDE"

// overrideTemplate is the generated fragment. Args: cgroup manager.
const overrideTemplate = `# Generated by inner — do not edit.
#
# Inside an inner sandbox podman rootless cannot use its default
# cgroup_manager = "systemd": creating the transient scope requires a
# StartTransientUnit call on the user D-Bus, and polkit resolves the caller
# through /proc in the HOST pid namespace. The sandbox has its own PID
# namespace (bwrap --unshare-pid), so the allow_active rule never matches and
# the call fails with "Access denied ... requires interactive authentication".
#
# With cgroupfs podman does not create a scope at all: the container stays in
# the cgroup of its parent process. The cost is that per-container resource
# limits (--memory, --cpus, --pids-limit) are not enforceable inside the
# sandbox — consistent with inner already skipping its own systemd-run scope
# when nested-user-ns is active.
[engine]
cgroup_manager = "%s"
`

// WriteOverride writes a containers.conf override fragment selecting the given
// cgroup manager into a fresh temporary directory and returns the file path.
// The caller owns the directory and must remove its parent (filepath.Dir of the
// returned path) when the run ends.
func WriteOverride(cgroupManager string) (string, error) {
	switch cgroupManager {
	case CgroupManagerCgroupfs, CgroupManagerSystemd:
	default:
		return "", fmt.Errorf("unknown cgroup manager %q", cgroupManager)
	}

	dir, err := os.MkdirTemp("", "inner-containers-*")
	if err != nil {
		return "", fmt.Errorf("creating containers conf dir: %w", err)
	}
	path := filepath.Join(dir, "containers.conf")
	content := fmt.Sprintf(overrideTemplate, cgroupManager)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		os.RemoveAll(dir) //nolint:errcheck
		return "", fmt.Errorf("writing containers.conf: %w", err)
	}
	return path, nil
}
