schema_version = "1"
name           = "java-maven"
description    = "Interactive shell with Java Maven and Podman support"
extends        = "shell-containers"

[mounts]
"~/.m2" = { dest = "~/.m2", mode = "rw" }

[env]
inherit = ["JAVA_HOME"]

[entrypoint]
history = [
  "mvn clean install -DskipTests",
  "mvn test",
  "mvn clean package",
]
