
baseURL = "https://enr.github.io/inner/"
languageCode = "en-us"
title = "inner"
theme = "inner"

[params]
  tagline = "Isolated sandboxes to run agents or untrusted code."
  repoURL = "https://github.com/enr/inner"
  currentAppVersion = "0.2.0"

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
